@startuml

(*) --> "Validate Access Token"
        --> if "valid?" then
                --> [yes] "Check for Required Scope for this FHIR Resource"
                --> if "OAuth2 scope correct?" then
                --> [yes] "Check HL7-v2 Message Transaction by looking at MSH and Z-segment(s)"
                    --> if "Is this a cofigured HL7-v2 message for this Resource?" then
                    --> [yes] "Forward HL7-v2 Message to PharmaNet"
                    --> "Return Response from PharmaNet Proxy"
                    --> (*)
                    else 
                    --> [no] "Return 401 Unauthorized"
                    --> (*)
                    endif
                else 
                --> [no] "Return 401 Unauthorized"
                endif
        else 
        --> [no] "Return 401 Unauthorized"
        --> (*)
        endif
