@startuml PNet_API_Components

package "PharmaNet APIs on OpenShift" {
    folder "HL7 FHIR Resource APIs" {
        [Claim]
        [Consent]
        [Location]
        [Medication]
        [MedicationDispense]
        [MedicationRequest]
        [MedicationStatement]
        [Patient]
        [Practioner]
    }
    folder "Common Components" {
        [Authorization]
        [Audit Logging]
        [HL7 FHIR Processing]
        [HL7-v2 Processing]
        [PharmaNet Proxy Delegate]
    }
}
newpage

package "HIBC PharmaNet Services" {
    [PharmaNet Proxy]
    [PharmaNet Web Services]
    [PharmaNet OLTP]
    [PharmaNet LDAP]
    [PharmaNet Database]
}

package "MOH API Authorization Platform" {
    [Keycloak]
    database "KeycloakDB" {
        [Keycloak Datastore]
    }
}
@enduml