@startuml PNet_API_Flow
autonumber
    actor Client
    Client <-> MOH_KeyCloak : Client Credentials Grant Authorization
    Client -> CITZ_Kong_API_Gateway : Prescription Record Request (TRX_X0.X5)
    CITZ_Kong_API_Gateway <-> CITZ_Kong_API_Gateway : Cursory JWT Validation
    CITZ_Kong_API_Gateway --> MedicationRequest_API : Prescription Record Request (Private Route)
    MedicationRequest_API <-> MOH_KeyCloak : Validate Authorization (JWT)
    MedicationRequest_API <-> MedicationRequest_API : Parse FHIR DocumentReference to extract HL7-v2 message
    MedicationRequest_API <-> MedicationRequest_API : Authorization Checks: Inspect HL7-v2 MSH to verify authorized transaction
    MedicationRequest_API -> HIBC_PharmaNet_Proxy : TRX_X0.X5 HL7-V2 message wrapped in JSON  (Private Route - SPAN BC)
    HIBC_PharmaNet_Proxy -> HIBC_PharmaNet_WebService : Pass HL7-v2 wrapped in JSON
    HIBC_PharmaNet_WebService -> HIBC_LDAP_Server : Verify web service credentials
    HIBC_PharmaNet_WebService -> HIBC_Pharmanet_OLTP_Application : TCP/IP SOCKET passing HL7-v2 message
    HIBC_PharmaNet_WebService <-- HIBC_Pharmanet_OLTP_Application : Return HL7-v2 Response
    HIBC_PharmaNet_Proxy <--  HIBC_PharmaNet_WebService : Return HL&-v2 Response
    MedicationRequest_API <-- HIBC_PharmaNet_Proxy : Return HL7-v2 Response
    MedicationRequest_API -> MedicationRequest_API : Build Response HL7 FHIR DocumentReference
    CITZ_Kong_API_Gateway <-- MedicationRequest_API : Return Response back thru Gateway
    Client <-- CITZ_Kong_API_Gateway : Return HL7 FHIR DocumentReference Response to Client
@enduml
