Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: trn
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-trn-secrets
    PharmaNet_PharmanetProxy__Username: common-trn-secrets
    PharmaNet_PharmanetProxy__Password: common-trn-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-trn-secrets

OpenShift:
  Environment: trn
  ImageProject: 2f77cb-tools

image:
  stream: patientservice

resources:
  limits:
  # updated from 500m to 100m to test out start
    cpu: 100m
  # updated from 1Gi to 100Mi to test out start
    memory: 150Mi
  requests:
    cpu: 20m
  # updated from 512Mi to 50Mi to test out start
    memory: 50Mi
