Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: vc1
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-vc1-secrets
    PharmaNet_PharmanetProxy__Username: common-vc1-secrets
    PharmaNet_PharmanetProxy__Password: common-vc1-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-vc1-secrets
    HEALTH_CHECK_CLIENT_ID: common-vc1-secrets
    HEALTH_CHECK_CLIENT_SECRET: common-vc1-secrets
    PharmaNet_PharmanetProxy__HealthCheckEndpoint: common-vc1-secrets

OpenShift:
  Environment: vc1
  ImageProject: d027a8-tools

image:
  stream: medicationstatementservice

resources:
  limits:
    cpu: 10m
    memory: 256Mi
  requests:
    cpu: 5m
    memory: 128Mi
