Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: dev
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-dev-secrets
    PharmaNet_PharmanetProxy__Username: common-dev-secrets
    PharmaNet_PharmanetProxy__Password: common-dev-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-dev-secrets

OpenShift:
  Environment: dev
  ImageProject: 2f77cb-tools

image:
  stream: medicationrequestservice

resources:
  limits:
    cpu: 90m
    memory: 256Mi
  requests:
    cpu: 45m
    memory: 128Mi

replicas: 8
