Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: vc2
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-vc2-secrets
    PharmaNet_PharmanetProxy__Username: common-vc2-secrets
    PharmaNet_PharmanetProxy__Password: common-vc2-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-vc2-secrets
    HEALTH_CHECK_CLIENT_ID: common-vc2-secrets
    HEALTH_CHECK_CLIENT_SECRET: common-vc2-secrets
    PharmaNet_PharmanetProxy__HealthCheckEndpoint: common-vc2-secrets

OpenShift:
  Environment: vc2
  ImageProject: 2f77cb-tools

image:
  stream: medicationrequestservice

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 1m
    memory: 100Mi
