Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: tr1
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-tr1-secrets
    PharmaNet_PharmanetProxy__Username: common-tr1-secrets
    PharmaNet_PharmanetProxy__Password: common-tr1-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-tr1-secrets
    HEALTH_CHECK_CLIENT_ID: common-tr1-secrets
    HEALTH_CHECK_CLIENT_SECRET: common-tr1-secrets
    PharmaNet_PharmanetProxy__HealthCheckEndpoint: common-tr1-secrets

OpenShift:
  Environment: tr1
  ImageProject: 2f77cb-tools

image:
  stream: patientservice

resources:
  limits:
    cpu: 10m
    memory: 256Mi
  requests:
    cpu: 5m
    memory: 128Mi
