kind: Build
apiVersion: build.openshift.io/v1
metadata:
  name: pnet-proxy
spec:
  source:
    git:
      uri: {{ .Values.buildSourceGitUri }}
      ref: {{ .Values.buildSourceGitRef }}
    contextDir: {{ .Values.buildSourceContextDir }}
  output:
    to:
      kind: ImageStreamTag
      name: 'pnet-proxy:latest'
  strategy:
    type: Docker
