Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: dev
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-dev-secrets
    PharmaNet_PharmanetProxy__Username: common-dev-secrets
    PharmaNet_PharmanetProxy__Password: common-dev-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-dev-secrets
    HEALTH_CHECK_CLIENT_ID: common-dev-secrets
    HEALTH_CHECK_CLIENT_SECRET: common-dev-secrets
    PharmaNet_PharmanetProxy__HealthCheckEndpoint: common-dev-secrets

OpenShift:
  Environment: dev
  ImageProject: 2f77cb-tools

image:
  stream: medicationdispenseservice

resources:
  limits:
    cpu: 16m
    memory: 256Mi
  requests:
    cpu: 2m
    memory: 128Mi

replicaCount: 1
