Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: prd
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-prd-secrets
    PharmaNet_PharmanetProxy__Username: common-prd-secrets
    PharmaNet_PharmanetProxy__Password: common-prd-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-prd-secrets

OpenShift:
  Environment: prd
  ImageProject: d027a8-tools

image:
  stream: practitionerservice

resources:
  limits:
    cpu: 100m
    memory: 150Mi
  requests:
    cpu: 20m
    memory: 50Mi

autoscaling:
  enabled: false
