Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: dev
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-dev-secrets
    PharmaNet_PharmanetProxy__Username: common-dev-secrets
    PharmaNet_PharmanetProxy__Password: common-dev-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-dev-secrets

OpenShift:
  Environment: dev
  ImageProject: 2f77cb-tools

image:
  stream: consentservice

resources:
  limits:
    cpu: 12m
    memory: 256Mi
  requests:
    cpu: 6m
    memory: 128Mi

replicaCount: 2
