Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: prd
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-prd-secrets
    PharmaNet_PharmanetProxy__Username: common-prd-secrets
    PharmaNet_PharmanetProxy__Password: common-prd-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-prd-secrets

OpenShift:
  Environment: prd
  ImageProject: d027a8-tools

image:
  stream: consentservice

resources:
  limits:
    cpu: 16m
    memory: 256Mi
  requests:
    cpu: 8m
    memory: 128Mi

replicaCount: 2
