Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: vs1
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-vs1-secrets
    PharmaNet_PharmanetProxy__Username: common-vs1-secrets
    PharmaNet_PharmanetProxy__Password: common-vs1-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-vs1-secrets
    HEALTH_CHECK_CLIENT_ID: common-vs1-secrets
    HEALTH_CHECK_CLIENT_SECRET: common-vs1-secrets
    PharmaNet_PharmanetProxy__HealthCheckEndpoint: common-vs1-secrets

OpenShift:
  Environment: vs1
  ImageProject: 2f77cb-tools

image:
  stream: consentservice

resources:
  limits:
    cpu: 10m
    memory: 256Mi
  requests:
    cpu: 5m
    memory: 128Mi
